Repository cloudera-labs/cdpctl, pull requests merged in 2021-08, with the labels that each got.

#3 CDPSDX-3111: Added version command.
  cdpctl/cli.py
Labels: enhancement

#9 CDPSDX-3117: CLI cleanups and enhancements.
  cdpctl/cli.py
  cdpctl/command/__init__.py
  cdpctl/command/validate.py
  install/cdpctl
Labels: bug

#19 Fix subnet CIDR range validation
  cdpctl/validation/infra/validate_aws_subnets.py
  tests/validation/infra/test_validate_aws_subnets.py
Labels: bug

#16 CDPCAM-69: skip CDP CIDR validation if tunnel enabled
  cdpctl/validation/conftest.py
  cdpctl/validation/infra/validate_aws_security_groups.py
  pytest.ini
  pytests.ini
Labels: bug

#21 Added checks to verify subnets data type
  cdpctl/validation/infra/validate_aws_subnets.py
Labels: enhancement

#24 CDPCAM-43: Added more links to the Issue Templates
  cdpctl/validation/infra/issue_templates.yml
  cdpctl/validation/issue_templates.yml
Labels: skip-changelog

#25 CDPCAM-72: Added warnings support
  cdpctl/validation/__init__.py
  cdpctl/validation/conftest.py
  cdpctl/validation/infra/issue_templates.yml
  cdpctl/validation/infra/validate_aws_subnets.py
  cdpctl/validation/renderer/templates/text.j2
  tests/validation/__init__.py
  tests/validation/infra/test_validate_aws_subnets.py
Labels: enhancement

#28 Minor bug fixes for issues.
  cdpctl/command/validate.py
  cdpctl/validation/__init__.py
  cdpctl/validation/infra/issue_templates.yml
  cdpctl/validation/issue_templates.yml
Labels: bug

#22 CDPCAM-71 Add Private Subnets validation with 'Auto-assign public IPs' disabled
  cdpctl/validation/infra/issue_templates.yml
  cdpctl/validation/infra/issues.py
  cdpctl/validation/infra/validate_aws_subnets.py
  tests/validation/infra/test_validate_aws_subnets.py
Labels: enhancement
